import { NextLinguiClientProvider } from 'next-lingui'
import { Geist, Geist_Mono } from 'next/font/google'
import { allMessages } from '~/lib/i18n'
import { cn } from '~/lib/utils'
import { Providers } from '~/providers'
import linguiConfig from '../../../lingui.config'
import type { Metadata } from 'next'

export async function generateStaticParams() {
  return linguiConfig.locales.map((locale) => ({ locale }))
}

export const metadata: Metadata = {
  metadataBase: new URL('https://starter-next-app-two.vercel.app/'),
  title: 'Create Next App',
  description: 'Generated by create next app',
  appleWebApp: {
    title: 'Starter Next App',
  },
  icons: [
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '96x96',
      url: '/favicon-96x96.png',
    },
    {
      rel: 'icon',
      type: 'image/svg+xml',
      url: '/favicon.svg',
    },
    {
      rel: 'shortcut icon',
      url: '/favicon.ico',
    },
    {
      rel: 'app-touch-icon',
      sizes: '180x180',
      url: '/apple-touch-icon.png',
    },
  ],
}

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export default async function Layout({
  params,
  children,
}: LayoutProps<'/[locale]'>) {
  const { locale } = await params

  return (
    <html
      lang={locale}
      className={cn(geistSans.variable, geistMono.variable)}
      suppressHydrationWarning
    >
      <body>
        <NextLinguiClientProvider
          locale={locale}
          messages={allMessages[locale]}
        >
          <Providers>{children}</Providers>
        </NextLinguiClientProvider>
      </body>
    </html>
  )
}
